import { DialogData } from "@/types";

export const dialogData: DialogData = {
  businness_activity: [
    { value: "accounting_auditing", label: "Accounting & Auditing" },
    { value: "advertising", label: "Advertising" },
    { value: "automobile_trading", label: "Automobile Trading" },
    { value: "aviation_consultancy", label: "Aviation Consultancy" },
    { value: "business_consultancy", label: "Business Consultancy" },
    { value: "cleaning_services", label: "Cleaning Services" },
    {
      value: "creative_arts",
      label: "Creative Arts & Entertainment Activities",
    },
    { value: "delivery_service", label: "Delivery Service" },
    { value: "digital_marketing", label: "Digital Marketing" },
    { value: "e_commerce", label: "E-Commerce" },
    { value: "educational_support", label: "Educational Support Activities" },
    { value: "engineering_consultancy", label: "Engineering Consultancy" },
    { value: "event_management", label: "Event Management" },
    { value: "food_trading", label: "Food Trading" },
    { value: "general_trading", label: "General Trading" },
    { value: "holding_company", label: "Holding Company" },
    { value: "hospitality_management", label: "Hospitality Management" },
    { value: "hr_consultancy", label: "HR Consultancy" },
    { value: "interior_design", label: "Interior Design Consultancy" },
    { value: "investment_consultancy", label: "Investment Consultancy" },
    { value: "it_consultancy", label: "IT Consultancy" },
    { value: "it_trading", label: "IT Trading" },
    { value: "jewellery", label: "Jewellery Trading" },
    { value: "legal_consultancy", label: "Legal Consultancy" },
    { value: "logistics_consultancy", label: "Logistics Consultancy" },
    { value: "maintenance", label: "Maintenance" },
    { value: "management_consultancy", label: "Management Consultancy" },
    { value: "media", label: "Media" },
    { value: "perfumes", label: "Perfumes & Cosmetics Trading" },
    { value: "photography", label: "Photography" },
    { value: "pr", label: "PR" },
    { value: "project_manager", label: "Project Manager" },
    { value: "raw_materials", label: "Raw Materials Trading" },
    { value: "real_estate", label: "Real Estate Trading" },
    { value: "restaurant", label: "Restaurant, Cafe, Cloud Kitchen" },
    { value: "retail_outlet", label: "Retail Outlet/Shop" },
    { value: "salon", label: "Salon" },
    { value: "software_publishing", label: "Software Publishing" },
    { value: "sports_management", label: "Sports Management" },
    { value: "technical_consultancy", label: "Technical Consultancy" },
    { value: "technical_services", label: "Technical Services" },
    { value: "textile_services", label: "Textile Services" },
    { value: "textile_trading", label: "Textile Trading" },
    { value: "tourism_recreation", label: "Tourism & Recreation" },
    { value: "videography", label: "Videography" },
  ],
  premises: [
    { value: "warehouse", label: "Warehouse" },
    { value: "business_centre", label: "Business Centre" },
    { value: "physical_office", label: "Physical Office" },
    { value: "shop_front", label: "Shop front" },
  ],
  owners: 0,
  vizas: 0,
  firstName: "",
  lastName: "",
  phoneNumber: "",
  email: "",
};
