const keywordsStrings = [
  "Almuda",
  "Accounting Uzbekistan",
  "Almuda Company",
  "almuda company",
  "buxgalteriya xizmatlari",
  "Financial Planning",
  "Accounting Services",
  "Tax Preparation",
  "Investment Management",
  "Retirement Planning",
  "Small Business Accounting",
  "Bookkeeping Services",
  "Tax Compliance",
  "Budgeting and Forecasting",
  "Financial Reporting",
  "Audit Services",
  "Estate Planning",
  "Personal Finance Tips",
  "Wealth Management",
  "Cryptocurrency Taxes",
  "Real Estate Accounting",
  "Financial Literacy",
  "IRS Regulations",
  "Financial Software",
  "Financial Education",
  "Business Valuation",
  "International Taxation",
  "Forensic Accounting",
  "Nonprofit Accounting",
  "Capital Gains Tax",
  "Financial Blogging",
  "Financial Advisor",
  "Fintech Trends",
  "Tax Deductions",
  "Credit Score Improvement",
  "Investment Strategies",
  "Student Loans and Finance",
  "Financial Calculators",
  "Cost Accounting",
  "Blockchain and Finance",
  "Payroll Services",
  "Accounting Software Reviews",
  "Family Financial Planning",
  "Retirement Accounts (e.g., 401(k), IRA)",
  "Risk Management in Finance",
];

const keywords = keywordsStrings.join(", ");

export { keywords };
