const keywords = [
  "Almuda",
  "almuda",
  "almuda in uzbekistan",
  "almuda uzbekistan",
  "almuda accounting",
  "start business in uzbekistan",
  "accounting in uzbekistan",
  "accounting",
  "accounting services",
  "accounting services in uzbekistan",
  "bugalteriya",
  "buxgalteriya",
  "buxgalteriya saytlar",
  "bugalteriya organamiz",
  "bugalter servis",
  "bugalteriya xizmatlari",
  "buxgalteriya xizmatlari",
  "xasanov javohir",
  "web developer",
  "nextjs applications",
  "accounting designs",
  "accounting websites designs",
  "accounting website with nextjs",
  "web developer",
  "nextjs developer",
];

export { keywords };
