import "./globals.css";
import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import { Footer, Navbar } from "@/layouts";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Almuda",
  description: "Generated by create next app",
  authors: [
    {
      name: "Xasanov Javohir",
      url: "https://portfoliowebapp.vercel.app",
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={[montserrat.variable, roboto.variable].join(" ")}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
