export { default as Hero } from "./Hero";
export { default as Features } from "./Features";
export { default as Phone } from "./Phone";
export { default as Pricing } from "./Pricing";
export { default as Partner } from "./Partner";
export { default as Analytics } from "./Analytics";
export { default as About } from "./About";
export { default as Careers } from "./Careers";
export { default as Contacts } from "./Contacts";
